# -*- coding: utf-8 -*-
"""Research.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_E4W-xQVQdyWcES2tvG475FSoLdbLlii
"""

!pip install -q google-generativeai

import google.generativeai as genai

genai.configure(api_key="AIzaSyDDsTCZ_HP3mK5u4k-MwbJksYxQOKLbwGc")

model = genai.GenerativeModel(
    "gemini-2.5-flash"
)

for model in genai.list_models():
    print(model.name)

response = model.generate_content("Hello")

print(response.text)

prompt = f"""
You are an explainable AI assistant for mental health risk assessment.

A machine learning model predicted elevated depression risk for a student.

Important contributing behavioral factors:

{"Financial Stress = 5.0 (increased depression risk)\
Academic Pressure = 2.0 (decreased depression risk)\
Have you ever had suicidal thoughts ? = 1.0 (increased depression risk)\
Age = 20.0 (increased depression risk)\
Work/Study Hours = 11.0 (increased depression risk)"}

Generate:
- a concise,
- psychologically coherent,
- human-readable explanation.

Do not diagnose the student.
Do not provide treatment advice.
Only explain the contributing behavioral factors.
"""

response = model.generate_content(prompt)

print(response.text)

txt={
  "suicidal_thoughts": {
    "source": "WHO",
    "evidence": "Individuals experiencing suicidal thoughts should seek immediate support from qualified mental health professionals.",
    "recommendation": "Consider reaching out to a counselor, mental health professional, or trusted support network."
  },

  "financial_stress": {
    "source": "NIMH",
    "evidence": "Financial difficulties can increase psychological stress and emotional burden.",
    "recommendation": "Explore student support programs and financial counseling resources available through your institution."
  },

  "academic_pressure": {
    "source": "Johns Hopkins Medicine",
    "evidence": "Persistent academic stress can negatively affect mental well-being.",
    "recommendation": "Break large tasks into smaller goals and make use of academic support services."
  },

  "sleep_duration": {
    "source": "WHO",
    "evidence": "Adequate sleep is strongly associated with improved mental health outcomes.",
    "recommendation": "Maintain a regular sleep schedule and avoid prolonged sleep deprivation."
  },

  "work_study_hours": {
    "source": "Mayo Clinic",
    "evidence": "Excessive workload may contribute to stress and emotional exhaustion.",
    "recommendation": "Maintain a balanced schedule and incorporate regular breaks."
  }
}

def retrieve_evidence(top_features):
    evidence = []

    for feature in top_features:

        key = feature.lower().replace(" ", "_")

        if key in txt:
            evidence.append(txt[key])

    return evidence

top_features = [
    "suicidal_thoughts",
    "financial_stress",
    "sleep_duration"
]

retrieved_docs = retrieve_evidence(top_features)

evidence_text = ""

for doc in retrieved_docs:

    evidence_text += f"""
Source: {doc['source']}
Evidence: {doc['evidence']}
Recommendation: {doc['recommendation']}
"""

prompt = f"""
You are an AI mental-health explanation assistant.

You must explicitly mention all of the following SHAP-important features in your explanation:

shap_features = [
    "Suicidal Thoughts",
    "Financial Stress",
    "Academic Pressure",
    "Sleep Duration",
    "Work/Study Hours"
]


Explain how each feature contributed to the prediction.
Do not omit any feature.

Retrieved Evidence:
{evidence_text}

Tasks:
You are a human-centered mental health explanation assistant.

Use the retrieved evidence as background knowledge.

Do not mention WHO, NIMH, or Johns Hopkins repeatedly unless necessary.

First explain the major factors contributing to the prediction.

Then provide a concise personalized recommendation.

Write in a supportive, professional, and non-clinical tone.

Do not diagnose depression.
Do not provide medical advice.
Do not invent information.
"""

response = model.generate_content(prompt)

final_output = response.text

print(final_output)

def grounding_score(shap_features, explanation):

    explanation = explanation.lower()

    mentioned = 0

    for feature in shap_features:
        if feature.lower() in explanation:
            mentioned += 1

    score = mentioned / len(shap_features)

    return score, mentioned


# Example

shap_features = [
    "Suicidal Thoughts",
    "Financial Stress",
    "Academic Pressure",
    "Sleep Duration",
    "Work/Study Hours"
]

explanation = """
The model predicts elevated depression risk primarily due to
suicidal thoughts, financial stress,reduced sleep duration,academic pressure and work/study pressure.
"""

score, mentioned = grounding_score(
    shap_features,
    explanation
)

print(f"Mentioned Features: {mentioned}")
print(f"Grounding Score: {score:.2f}")

sample_score = grounding_score(
    shap_features,
    explanation
)[0]

scores=[]
scores.append(sample_score)

avg_grounding_score = sum(scores) / len(scores)

print("Average Grounding Score:",
      round(avg_grounding_score,3))